services:
  backend:
    build: .
    ports:
      - '3000:3000'
    networks:
      - biblioteca
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@database:5432/biblioteca
    develop:
      watch:
        - path: ./src
          action: rebuild
    depends_on:
      - database
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=biblioteca
    ports:
      - '5432:5432'
    networks:
      - biblioteca
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
networks:
  biblioteca:
    driver: bridge
